id: ID6BB1679
ocr_import_info:
  timestamp: '2023-10-06T15:22:15.156078+00:00'
  batch_id: batch-bae9
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharmakyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-10-07 07:13:18.007697+00:00
last_modified: 2023-10-07 07:13:18.007706+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS31216
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8LS31216
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སེམས་ཉིད་ངའ་གསོའི་དོན་ཁྲིད།
  languages:
  - bo
  author: ཀློང་ཆེན་རབ་འབྱམས་པ་དྲི་མེད་འོད་ཟེར།
statistics:
  ocr_word_mean_confidence_index: 0.9624642953113481
  ocr_word_median_confidence_index: 0.9979076499999999
bases:
  I8LS31232:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS31232
      total_pages: 78
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS31232.txt
    statistics:
      ocr_word_median_confidence_index: 0.9979076499999999
      ocr_word_mean_confidence_index: 0.9624642953113481
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
